url: https://sanduni-p.github.io/AI_Beyond_Omics_Workshop/
project:
  type: website

website:
  title: "ABACBS Conference 2024 - AI Beyond Omics Workshop"
  navbar:
    left:
      - href: index.html
        text: Home
      - text: Workshop Materials
        href: materials.html
        
format:
  html:
    theme: 
      - cerulean
      - utils/css/custom.scss
    toc: true
    toc-expand: 1
    toc-title: Contents
    embed-resources: true
    css: utils/css/custom.css
    smooth-scroll: true
    df-print: kable
execute: 
  freeze: auto

