
# Call for Abstracts for Short Talks

We invite abstract submissions for **5-minute short talks** on the topic of applying AI beyond bioinformatics and omics projects. Topics listed below are indicative only, as we welcome any creative ideas and projects where bioinformaticians have been involved: AI-assisted coding, AI-assisted pipeline execution, clinical informatics, experimental design optimisation, analysis of imaging and enterprise data, business intelligence, operations optimisation, professional development and career related ideas.

-   **Submit abstracts to** <https://forms.gle/V1Uo49GJjsJy2BuV7>. 
-   **Abstract submission deadline:** [25th October Sunday 11.55 PM]{style="color:red;"}.
-   Abstracts should be concise (no more than 250 words). 
-   Five talks will be selected based on innovation, relevance to the workshop theme, and clarity of the application.

# Overview of the Workshop

## Workshop Summary

This workshop aims to explore the broad applications of artificial intelligence (AI) technologies that are relevant to bioinformaticians. The event will feature short talks where participants will present projects that demonstrate the use of AI, beyond its applications in mainstream bioinformatics. These projects may involve various AI subfields, such as machine learning (ML), deep learning, computer vision, generative AI, natural language processing, neural networks, large language models (LLMs). The workshop will include a hands-on session focused on employing generative AI tools to augment bioinformatics research with particular emphasis on literature searches, coding, data analysis and visualization. Participants will also learn and engage in discussions on data governance, the ethical and regulatory considerations of AI and the usage of advanced analytics platforms in healthcare settings.

## Objectives

-   Demonstrate innovative uses of AI by bioinformaticians in diverse applications, including AI-assisted coding, clinical informatics, experimental design optimisation, analysis of imaging and enterprise data among others.
-   Engage in practical sessions to utilize generative AI tools aimed at enhancing bioinformatics research.
-   Learn key considerations in data governance and the ethical implications of AI and the use of advanced analytics platforms.
-   Foster collaboration and knowledge exchange among participants to build a network of professionals interested in innovative AI applications.

## Agenda

#### 1. 1.30 PM – 1.35 PM Introduction

-   Welcome participants and introduce the goals and structure of the workshop.

#### 2. 1.30 PM – 1.35 PM Introduction

-   Five x 5-minute talks by selected speakers, focusing on applications of AI beyond bioinformatics projects. \[30 minutes\]
-   A brief Q&A panel session to discuss insights and experiences shared during the talks. \[15 minutes\]

#### 3. 9.55 AM – 10.50 AM Data Governance and Ethical Consideration

-   Presentation on data governance and navigating ethics and regulations of AI. \[20 minutes\]
-   Presentation on exploring advanced analytics platforms and their role in data governance. \[20 minutes\]
-   Interactive discussion with audience participation to explore these topics further. \[15 minutes\]

#### 4. 3.00 PM – 3.30 PM Break

#### 5. 3.30 PM – 4.40 PM Hands-On Workshop on Using Generative AI Tools in Research

-   Live demonstration and hands-on session using generative AI tools in bioinformatics research, with a focus on literature searches, coding, data analysis and visualization. The session will showcase the applications of ResearchRabbit, SCISPACE, Elicit, Litmaps, Perplexity, among others. \[40 minutes\]
-   Participants will work with example datasets to gain first-hand experience with the capabilities and functionality of generative AI tools. \[30 minutes\]

#### 6. 4.40 PM - 5.00 PM Short-Talk Award

#### 7. 5.00 PM - 5.10 PM Wrap-Up and Open Discussion

-   Summary of key takeaways.
-   Open floor for additional questions and networking.

## Target Audience

This workshop is intended for bioinformaticians, researchers, and data scientists interested in the intersection of AI and bioinformatics and looking to expand their skills into other areas using AI. Participant Requirements:

-   Laptop with internet access for the hands-on session.
-   Basic understanding of ML and bioinformatics concepts.

## Organizers

### Dr. Jason Li

*Senior Bioinformatics Core Manager, Peter MacCallum Cancer Centre*

Dr. Jason Li is the Head of Bioinformatics Core Facility and the Lead of Artificial Intelligence Transformation Program at Peter MacCallum Cancer Centre (PMCC) in Melbourne. In addition to supporting high-throughput cancer omics analyses, Jason is spearheading various AI initiatives at PMCC to advance the organisational AI maturity in both research and clinical AI. Jason’s expertise lies in the management of diverse talent, demand and expectations in the context of a fee-for-service bioinformatics and AI facility. Jason and his team have also led and published studies in the field of DNA copy number analysis and pipeline development for high throughput data. His current research activities include the use of Large Language Models in clinical report analysis, and deep learning in cancer multi-omics and medical imaging.

### Dr. Sanduni Rajapaksa

*Informatics Consultant, Peter MacCallum Cancer Centre*

Dr. Sanduni Rajapaksa is an Informatics Consultant and a co-lead of the AI education program at the Peter MacCallum Cancer Centre. Sanduni received her PhD specialized in Bioinformatics from the Laboratory of Computational Biology in the Department of Data Science and AI at Monash University. Continuing her research journey, Sanduni remains passionate about exploring the vast realm of proteins and omics data using statistical inference methods and AI techniques. She actively continues to foster an understanding of AI and bioinformatics techniques among Peter Mac staff.

### Rashindrie Perera

*Machine Learning Scientist, Peter MacCallum Cancer Centre*

Rashindrie Perera is a Machine Learning Scientist at the Bioinformatics Core Facility and a member of the Digital & Healthcare Innovations Program at the Peter MacCallum Cancer Centre. She is currently a final-year PhD candidate in the Optimisation and Pattern Recognition Group at the Faculty of Engineering and IT, University of Melbourne. Her PhD research focuses on training deep neural networks with limited datasets. Rashindrie's primary research interests include deep learning and computer vision.

### Richard Lupat

*Senior Bioinformatics Software Engineer, Peter MacCallum Cancer Centre*

Richard Lupat is a Senior Bioinformatics Software Engineer from the Bioinformatics Core Facility at the Peter MacCallum Cancer Centre. He received his M.Phil. degree in machine learning from The Sir Peter MacCallum Department of Oncology, University of Melbourne, in 2021. Richard currently leads a team that is responsible for developing production software and workflows for automating the analysis of cancer sequencing data. His current research interests include the portability of workflow languages, and application of Artificial Intelligence in cancer genomics.

### Dr. Adrien Oliva

*Cloud Bioinformatician - Postdoctoral Fellow, CSIRO*

Dr. Adrien Oliva is a Cloud Bioinformatician and Postdoctoral Fellow in the Transformational Bioinformatics group at CSIRO, the Commonwealth Scientific and Industrial Research Organisation. He completed his PhD in 2022, specialising in pangenome graph research. Adrien's work focuses on applying cloud technologies in genomics to enhance data security, optimize cost-effective algorithms, and support the broad adoption of genomic data. His current research centers on GeneGuardian, a conceptual framework for secure and ethical genomic data management that ensure participant control and data sovereignty in large-scale genomic studies.

### Dr. Andrew Perry

*Research Software Specialist, Monash Genomics and Bioinformatics Platform, Monash University*

Dr. Andrew Perry is a Research Software Specialist at the Monash Genomics and Bioinformatics Platform, Monash University. He received his PhD in structural biology from the University of Melbourne. Andrew's work focuses on developing user-friendly genomics pipelines, with emphasis on transcriptomics and metagenomics. He is currently exploring applications of transformer architectures, large language models, and embedding-based search and retrieval techniques to enhance biological sequence discovery and annotation.
